env: "ha"

## Keepalived common settings
nginx_vip: "10.2.141.101"
mysql_vip: "10.2.141.102"
vrrp_nic: "ens192"

## Wordpress settings
wp_home: "/var/www/wordpress"
wp_db_name: "wordpress"
wp_db_user: "wpuser"
wp_db_password: "{{ vault_mysql_wpuser_password }}"
wp_db_host: "{{ mysql_vip }}"

## PHP-FPM settings
php_enable_webserver: false
php_enable_php_fpm: true
php_fpm_listen: "0.0.0.0:9000"
php_fpm_listen_allowed_clients: "{{ fpm_allowed_ip }}"
php_packages_extra:
  - php-mysql