- src: geerlingguy.mysql
  name: mysql
- src: geerlingguy.nginx
  name: nginx
- src: geerlingguy.php
  name: php
- src: https://github.com/evrardjp/ansible-keepalived.git
  version: master
  name: keepalived