---
- hosts: all
  tasks:
    - name: Import secrets
      include_vars:
        file: "./inventory/secrets.yml"
    - name: Set ips in group
      set_fact:
        fpm_backends: "{{ groups['fpm'] | map('extract', hostvars, ['ansible_default_ipv4', 'address'])|map('regex_replace', '^(.*)$','\\1:9000')|list}}"

    - name: Return upstreams
      debug:
        msg: "{{ fpm_backends }}"
  tags: 
    - always

- hosts: mysql
  become: true
  roles:
    - role: mysql
      tags:
        - mysql

- hosts: fpm
  become: true
  pre_tasks:
    - unarchive: 
        src: "https://wordpress.org/latest.tar.gz"
        dest: "/var/www"
        remote_src: yes
    - template:
        src: "templates/wp-config.php.j2"
        dest: "{{ wp_home }}/wp-config.php"
  tags:
    - wp
  roles:
    - role: php
      tags:
        - php
        - fpm
        - wp
  post_tasks:
    - file:
        path: "{{ wp_home }}"
        owner: www-data
        group: www-data
        recurse: yes

- hosts: nginx
  become: true
  roles:
    - role: nginx
      tags:
        - nginx
