---
- hosts: all
  tasks:
    - name: Import secrets
      include_vars:
        file: "./inventory/secrets.yml"
    - name: Set ips in group
      set_fact:
        fpm_backends: "{{ groups['fpm'] | map('extract', hostvars, ['ansible_default_ipv4', 'address'])|map('regex_replace', '^(.*)$','\\1:9000')|list}}"

    - name: Return upstreams
      debug:
        msg: "{{ fpm_backends }}"

  tags: 
    - always

- hosts: all
  become: true
  roles:
    - role: docker
      tags:
        - docker
    - role: mysql
      tags:
        - mysql
    - role: systemd
      tags:
        - fpm
        - wp
    - role: nginx
      tags:
        - nginx
